### ISSUE TITLE
PHP docblock invalid one line description

### ISSUE THREAD

**Issue by mudrd8mz** [moodlecincopa/moodle-filter_cincopa#1]
It seems that the file-level docblock was copy & pasted to other files without editign the one-line description of the file. So that it reads just "Version information" in filter.php, settings.php and lang/en/filter_cincopa.php too.

**Comment by piktogramstudio** [comment]
@mudrd8mz this issue should be fixed now. Please review.

**Comment by mudrd8mz** [comment]
Should this be marked as closed now?
