### ISSUE TITLE
Performance: Quick pre-check for the cincopa keyword

### ISSUE THREAD

**Issue by mudrd8mz** [moodlecincopa/moodle-filter_cincopa#2]
The `filter_cincopa::filter()` starts with `preg_match_all()` call which is applied on every piece of text produced by Moodle. For performance reasons, it is recommended that filters like this first execute a quick precheck via `strpos()` to see if the given text actually contains a keyword.

Checking for `cincopa` keyword in this case looks reasonable. If it is not found, the method would quit early without the need to deal with expensive regex.

**Comment by piktogramstudio** [comment]
@mudrd8mz this issue should be fixed now. Please review.

**Comment by mudrd8mz** [comment]
Should this be marked as closed now?
